//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebServer.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buffer has overflown.
        /// </summary>
        internal static string BufferFull {
            get {
                return ResourceManager.GetString("BufferFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error in connecting with client.
        /// </summary>
        internal static string ClientError {
            get {
                return ResourceManager.GetString("ClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error in accepting request.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error in closing socket or socket already closed.
        /// </summary>
        internal static string SocketClosingError {
            get {
                return ResourceManager.GetString("SocketClosingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error in creating socket.
        /// </summary>
        internal static string SocketCreatingError {
            get {
                return ResourceManager.GetString("SocketCreatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is not implemented.
        /// </summary>
        internal static string UnimplementedMethod {
            get {
                return ResourceManager.GetString("UnimplementedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string WrongRequest {
            get {
                return ResourceManager.GetString("WrongRequest", resourceCulture);
            }
        }
    }
}
